# Generated by Django 3.1.2 on 2020-11-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201104_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulations',
            name='star_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='09:33'),
        ),
    ]
