# Generated by Django 3.1.2 on 2020-11-05 13:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201105_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulations',
            name='video_con',
            field=models.FileField(upload_to=users.models.congratulationFile),
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='13:57'),
        ),
    ]
