# Generated by Django 3.1.2 on 2020-11-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201112_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='07:37'),
        ),
    ]
