# Generated by Django 3.1.2 on 2020-11-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201116_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='confirm',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='07:45'),
        ),
    ]
