# Generated by Django 3.1.2 on 2020-11-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201116_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='stars',
            name='price_another',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='08:30'),
        ),
    ]
