# Generated by Django 3.1.2 on 2020-11-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201116_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='08:34'),
        ),
    ]
