# Generated by Django 3.1.2 on 2020-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201116_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='10:53'),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('star_id', 'cust_id')},
        ),
    ]
