# Generated by Django 3.1.2 on 2020-11-18 07:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201116_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongratulationPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='07:46'),
        ),
        migrations.CreateModel(
            name='CongratulationPageVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=users.models.exVideoFile)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.congratulationpage')),
            ],
        ),
    ]
