# Generated by Django 3.1.2 on 2020-11-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201118_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulationpage',
            name='content',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='07:49'),
        ),
    ]
