# Generated by Django 3.1.2 on 2020-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201118_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatars',
            options={'verbose_name': 'Аватар', 'verbose_name_plural': 'Аватары'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='catphoto',
            options={'verbose_name': 'Фото категории', 'verbose_name_plural': 'Фото категорий'},
        ),
        migrations.AlterModelOptions(
            name='congratulationpage',
            options={'verbose_name': 'Видео-поздравление(пример)', 'verbose_name_plural': 'Видео поздравления(примеры)'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='requestsform',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='stars',
            options={'verbose_name': 'Звезда', 'verbose_name_plural': 'Звезды'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Видео приветствие', 'verbose_name_plural': 'Видео приветствия'},
        ),
        migrations.AddField(
            model_name='stars',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='15:08'),
        ),
    ]
