# Generated by Django 3.1.2 on 2020-12-15 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201208_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='stars',
            name='sorted',
            field=models.IntegerField(default=1, verbose_name='Сортировка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='08:28'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='cat_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='days',
            field=models.CharField(default='0', max_length=8, verbose_name='Дней выполнения заказа'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='description',
            field=models.TextField(max_length=2048, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ценник'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='price_another',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ценник еще'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='profession',
            field=models.CharField(max_length=32, verbose_name='Проффесия'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Топ10'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='video_hi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.videos', verbose_name='Видео-приветсвие'),
        ),
    ]
