# Generated by Django 3.1.2 on 2020-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201215_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='by_time',
            field=models.TimeField(default='07:26'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='sorted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
    ]
